name: Supabase Countdown Function

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute

jobs:
  countdown-job:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Edge Function
        run: |
          echo "Calling Supabase Edge Function at $(date)"
          curl -i -X POST https://xxmdaccbrarqjjbmwqom.supabase.co/functions/v1/update-overdue-documents \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
